In [1]:
import numpy as np

In [5]:
#mathematical fnx

#aggregation
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.argmin(arr))


15
120
1
0


In [7]:
#power function
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [10]:
#log and exponential
print(np.log(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [12]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))
print(np.abs(arr))  #absoulte


3.0
4.0
3.0
3.0
[1 2 3 4 5]
