In [1]:
import numpy as np

In [6]:
#multi_dimensional array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

#sum of column
sum_of_column = np.sum(arr2D,axis = 0)
print(sum_of_column)

#sum of rows
sum_of_rows = np.sum(arr2D,axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [9]:
#slicing in n-dimensional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:2])

[[2]
 [5]]


In [17]:
#3d array
arr3D = np.array([[[2,4],[3,6]],[[3,7],[4,8]]])
print(arr3D,arr3D.shape)

#indexing 
print(arr3D[0,1,1])

#slicing
print(arr3D[:,0,:]) #for first row of both layers

[[[2 4]
  [3 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)
6
[[2 4]
 [3 7]]
