In [1]:
import numpy as np

In [2]:
#reshaping
arr = np.array([[1,2,3] , [4,5,6]])
print(arr)
reshape = arr.reshape((3,2))
print(reshape,reshape.shape)

#flatten
flattened = arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [7]:
#indexing in array
arr = np.array([1,2,3,4,5])
print(arr[0])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1][1])

1
5


In [9]:
#fancy indexing
arr = np.array([1,2,3,4,5])
idx = [1,2,4]
print(arr[idx])

[2 3 5]


In [10]:
#boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr >3])

[4 5]


In [12]:
#slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4])


[2 3 4]


In [24]:
#copy Vs view
#python list
# num = [1,2,3,4,5]
# sub_list = num[1:3]
# print(sub_list)
# sub_list[0] = 200
# print(sub_list)
# print(num)

#numpy array

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)



[2 3]
[200   3]
[1 2 3 4 5]
