In [1]:
import numpy as np

In [2]:
#vectorization
arr = np.array([1,2,3,4])
print(arr **2)


[ 1  4  9 16]


In [7]:
#broadcasting
arr = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr + arr2)
print(arr.shape)
print(arr2.shape)

[[ 2  4  6  8]
 [ 6  8 10 12]]
(4,)
(2, 4)
