In [1]:
import numpy as np

In [11]:
#reshaping
arr = np.array([[1,2,3] , [4,5,6]])
print(arr)
reshape = arr.reshape((3,2))
print(reshape,reshape.shape)

#flatten
flattened = arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]
